[package]
name = "chillaekser"
version = "0.1.0"
edition = "2021"

[dependencies] 
anyhow = {version = "1.0.97", features = ["backtrace"]}
serde = "1.0.219"
serde_json = "1.0.140"
serenity = "0.12.4"
tokio = {version = "1.44.1", features = ["full"]}
